package hotelManagement.model;

import java.sql.Timestamp;

public class Billing {
    private int billId;
    private int reservationId;
    private int guestId;
    private double totalAmount;
    private double seasonalDiscount;
    private double finalAmount; // This is generated by DB
    private String paymentMethod;
    private String transactionStatus;
    private Timestamp createdAt;

    // Constructor
    public Billing(int reservationId, int guestId, double totalAmount, double seasonalDiscount, String transactionStatus) {
        this.reservationId = reservationId;
        this.guestId = guestId;
        this.totalAmount = totalAmount;
        this.seasonalDiscount = seasonalDiscount;
        this.transactionStatus = transactionStatus;
    }

    // Getters and Setters
    public int getBillId() { return billId; }
    public void setBillId(int billId) { this.billId = billId; }

    public int getReservationId() { return reservationId; }
    public void setReservationId(int reservationId) { this.reservationId = reservationId; }

    public int getGuestId() { return guestId; }
    public void setGuestId(int guestId) { this.guestId = guestId; }

    public double getTotalAmount() { return totalAmount; }
    public void setTotalAmount(double totalAmount) { this.totalAmount = totalAmount; }

    public double getSeasonalDiscount() { return seasonalDiscount; }
    public void setSeasonalDiscount(double seasonalDiscount) { this.seasonalDiscount = seasonalDiscount; }

    public double getFinalAmount() {
        return calculateFinalAmount();
    }

    // Calculate the final amount by applying the seasonal discount
    private double calculateFinalAmount() {
        return totalAmount - seasonalDiscount;
    }

    public void setFinalAmount(double finalAmount) { this.finalAmount = finalAmount; }

    public String getPaymentMethod() { return paymentMethod; }
    public void setPaymentMethod(String paymentMethod) { this.paymentMethod = paymentMethod; }

    public String getTransactionStatus() { return transactionStatus; }
    public void setTransactionStatus(String transactionStatus) { this.transactionStatus = transactionStatus; }

    public Timestamp getCreatedAt() { return createdAt; }
    public void setCreatedAt(Timestamp createdAt) { this.createdAt = createdAt; }
}
